version: "3"

tasks:
  test:
    desc: Run tests
    cmds:
      - go test ./...

  test:cover:
    desc: Run tests with coverage
    cmds:
      - go test -race -cover ./...

  test:verbose:
    desc: Run tests with verbose output
    cmds:
      - go test -v ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  check:
    desc: Run all checks (fmt, vet, test)
    cmds:
      - task: fmt
      - task: vet
      - task: test:cover

  tidy:
    desc: Run go mod tidy
    cmds:
      - go mod tidy

  tag:
    desc: Create a new git tag (usage: task tag -- v1.0.0)
    cmds:
      - git tag {{.CLI_ARGS}}
      - echo "Created tag {{.CLI_ARGS}}"

  tag:push:
    desc: Create and push a new git tag (usage: task tag:push -- v1.0.0)
    cmds:
      - git tag {{.CLI_ARGS}}
      - git push origin {{.CLI_ARGS}}
      - echo "Created and pushed tag {{.CLI_ARGS}}"

  tag:latest:
    desc: Show the latest tag
    cmds:
      - git describe --tags --abbrev=0 2>/dev/null || echo "no tags"
